# Generated by Django 6.0.3 on 2026-03-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='Technical_skill',
        ),
    ]
