# Generated by Django 6.0.3 on 2026-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_name_skill_technical_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Technical_skill',
            new_name='technical_skills',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year_attended',
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('elementary', 'Elementary'), ('junior_high', 'Junior High School'), ('senior_high', 'Senior High School'), ('college', 'College')], default='elementary', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='year_started',
            field=models.CharField(default='elementary', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
