# Generated by Django 6.0.3 on 2026-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools_used',
            field=models.CharField(help_text='Separate tools with commas e.g. Python,Django,MySQL', max_length=200),
        ),
    ]
