# Generated by Django 6.0.3 on 2026-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_tools_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools_used',
            field=models.CharField(max_length=200),
        ),
    ]
